# Generated by Django 2.2.7 on 2021-04-28 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, choices=[('Математика', 'Математика'), ('Русский язык', 'Русский язык'), ('Литература', 'Литература'), ('История', 'История'), ('Физическая культура', 'Физическая культура'), ('Музыка', 'Музыка'), ('Технология', 'Технология'), ('Химия', 'Химия'), ('Биология', 'Биология'), ('Физика', 'Физика'), ('Экология', 'Экология'), ('География', 'География'), ('Естествознание', 'Естествознание'), ('Астрономия', 'Астрономия'), ('Окружающий мир', 'Окружающий мир'), ('Изобразительное искусство', 'Изобразительное искусство'), ('Основы безопасности жизнедеятельности', 'Основы безопасности жизнедеятельности'), ('Информатика', 'Информатика'), ('Робототехника', 'Робототехника'), ('Экономика', 'Экономика')], max_length=100)),
                ('name', models.TextField(blank=True, max_length=100)),
                ('register_end_date', models.DateField(default=None)),
                ('competition_date', models.DateField(default=None)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('rank', models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('н', 'нет')])),
                ('support_email', models.EmailField(default=None, max_length=254)),
                ('address', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='registerOlympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='register_Olympiad', to='olympiads.Olympiad')),
                ('usr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('usr_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to='autorization.Profile')),
            ],
        ),
    ]
