# Generated by Django 2.2.7 on 2021-05-30 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0002_olympiad_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerolympiad',
            name='usr',
        ),
        migrations.AddField(
            model_name='registerolympiad',
            name='usr',
            field=models.ManyToManyField(related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
