# Generated by Django 2.2.7 on 2021-05-30 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympiads', '0003_auto_20210530_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerolympiad',
            name='usr',
        ),
        migrations.AddField(
            model_name='registerolympiad',
            name='usr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
