# Generated by Django 2.2.7 on 2021-05-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0004_auto_20210530_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerolympiad',
            name='olympiad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='register_Olympiad', to='olympiads.Olympiad'),
        ),
    ]
