# Generated by Django 2.2.7 on 2021-05-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0005_auto_20210530_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerolympiad',
            name='usr_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to='autorization.Profile'),
        ),
    ]
