# Generated by Django 2.2.7 on 2021-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0007_successolympiad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerolympiad',
            name='type_success',
            field=models.TextField(choices=[('Победитель', 'Победитель'), ('Абсолютный победитель', 'Абсолютный победитель'), ('Диплом 1 степени', 'Диплом 1 степени'), ('Диплом 2 степени', 'Диплом 2 степени'), ('Диплом 3 степени', 'Диплом 3 степени'), ('Призер', 'Призер'), ('Участник', 'Участник'), ('Не определен', 'Не определен')], default=('Не определен', 'Не определен')),
        ),
        migrations.DeleteModel(
            name='SuccessOlympiad',
        ),
    ]
