# Generated by Django 2.2.7 on 2021-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0008_auto_20210601_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olympiad',
            old_name='grade',
            new_name='grade_beg',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='grade_end',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default=None),
        ),
    ]
