# Generated by Django 2.2.7 on 2021-06-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0009_auto_20210601_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olympiad',
            old_name='grade_beg',
            new_name='grade',
        ),
        migrations.RemoveField(
            model_name='olympiad',
            name='grade_end',
        ),
    ]
