# Generated by Django 2.2.7 on 2021-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiads', '0010_auto_20210601_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiad',
            name='grade',
            field=models.DecimalField(decimal_places=10, default=None, max_digits=11),
        ),
    ]
